### ISSUE TITLE
Update benchmark results with sorted results

### ISSUE THREAD

**Issue by Kerollmops** [vorner/corona#2]
I just read [your interesting blog post](https://vorner.github.io/async-bench.html) and found useful to have the benchmark results sorted.

I have done this job for you if you want: https://gist.github.com/Kerollmops/699c52da7f2cd36ab306e48976a286e5

**Comment by vorner** [comment]
Hello.

Few questions:
* Do you mean to show them sorted on blog post, or the stored ones in the repository? On the blog post, it could make some sense, the ones in repository are the „raw data“ to generate the graph.
* I wonder if it is really better to sort them. I mean, this shows the „ladder“, which is useful, but on the other hand, when trying to locate specific one, it takes more work. Do you have a strong argument for sorting them, or do you just „feel“ they are better that way (I'm not saying the later one is wrong, I'm just trying to judge how strong the reason for sorting them is and if I want to do it).

**Comment by Kerollmops** [comment]
I wanted them to be sorted on the blog post only. I think having them sorted is useful when you want to search for the better, it's painful when it isn't sorted.

**Comment by vorner** [comment]
Well, in the end, why not. It seems slightly better to have them sorted (though this makes it a bit harder to compare two specific implementations directly).

So, thank you, I updated the blog post.
