### ISSUE TITLE
Setting stack size causes assertion error

### ISSUE THREAD

**Issue by GallagherCommaJack** [vorner/corona#4]
Minimal example:
```
use corona::{coroutine::*, prelude::*};
use futures::future::Future;

#[test]
fn main() {
    Coroutine::new()
        .stack_size(10_000)
        .run(|| {})
        .expect("failed")
}
```

Having this bug with `corona = 0.4` and `futures = 0.1`.

**Comment by GallagherCommaJack** [comment]
It looks like this issue is caused by a failing assert in `Switch.rs`. If I had to guess, `boost` is allocating larger stack frames for alignment reasons, and rather than just checking that the frame is large enough the assert is checking for exact equality.

**Comment by vorner** [comment]
Hello

This is known and actually desired behaviour. From the documentation:

>  Note that the size must be a valid stack size. This is platform dependent, but usually must be multiple of a page size. That usually means a multiple of 4096.

Do you think the note should be more prominent? Maybe it should go into the `Panics` section.

**Comment by vorner** [comment]
Sorry, no, assert is not what should happen, error should. I'll look into it.

Just to confirm, you're not getting that panic from your expect?

**Comment by GallagherCommaJack** [comment]
> Just to confirm, you're not getting that panic from your expect?

I'm not. The panic is from an assertion failure.

> This is known and actually desired behaviour. From the documentation:

I guess it is noted, but is it desirable? Boost reliably rounds up in stack size, and since it's virtual memory there's no penalty for it being larger. I've run benchmarks on my fork that multiplied the default `stack_size` by 1000 and the performance was equivalent.

If this is desired, maybe a function that multiplies the default stack size is a better/safer choice than one that sets it directly? Setting it directly is basically never a good idea since valid stack size is so platform dependent.

**Comment by vorner** [comment]
> Boost reliably rounds up in stack size

I vaguely remember the older version of context I was using when starting this has blown up with incorrect stack sizes, it does round up now, so it's good. I'm relaxing the requirement.

> and since it's virtual memory there's no penalty for it being larger.

Yes, but virtual memory is assigned by the whole pages. So the round-up still affects the memory consumption, but considering there's no way to get less (except for nasty things like allocating the stacks manually mid-page), it's probably good enough.

**Comment by GallagherCommaJack** [comment]
#6 solves this. There's separately the question of whether default stack size should be larger (because virtual memory there's essentially no reason not to on a 64-bit machine, and little reason on 32 bit.

**Comment by vorner** [comment]
> There's separately the question of whether default stack size should be larger

I don't know. Even virtual memory is not completely free. But I've avoided that question mostly because I didn't have any data to decide on what would be the good default size so I've left it up to the lower-level libraries.

If you feel like it's worth solving, feel free to open a different issue for that question and suggest what the default should be and why. Though taking the 32bit machines into consideration might be reasonable ‒ I know the library works fine on eg. 32bit arm devices which are still around even if 32bit intel is bit rare today.
